version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Setting PYTHONPATH...
      - export PYTHONPATH=$PYTHONPATH:$CODEBUILD_SRC_DIR  # Replace with the correct path if needed
      - echo Running unit tests...
      - pytest tests --maxfail=1 --disable-warnings --junitxml=report.xml
  build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - app.py
    - utils.py
    - requirements.txt
    - report.xml
    - Procfile
    - mlb.pkl
