version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running unit tests...
      - pytest tests --maxfail=1 --disable-warnings --junitxml=report.xml
  build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - app.py
    - utils.py
    - requirements.txt
    - report.xml
